# Any change to "token" or "chatChannelID" requires a server restart
token: "YOUR_BOT_TOKEN"
chatChannelID: "YOUR_CHAT_CHANNEL_ID"

messages:
  server-start: "**âš¡ Server started**" # Server startup
  server-stop: "**ğŸ›‘ Server stopped**" # Server shutdown

  # Player chat message
  # Placeholders:
  # %player_name% - In-game username
  # %player_display_name% - Display name
  # %message% - Message sent by player
  player-message: "**%player_display_name%** > %message%"

  # Player joins the server
  # Placeholders:
  # %player_name% - In-game username
  # %player_display_name% - Display name
  player-join: "**ğŸŸ¢ %player_display_name%**"

  # Player leaves the server
  # Placeholders:
  # %player_name% - In-game username
  # %player_display_name% - Display name
  player-quit: "**ğŸ”´ %player_display_name%**"

  # Player dies
  # Placeholders:
  # %player_name% - In-game username
  # %player_display_name% - Display name
  # %death_message% - How the player died
  player-death: "**ğŸ’€ %player_display_name%** %death_message%"

  # Player completes an advancement
  # Placeholders:
  # %player_name% - In-game username
  # %player_display_name% - Display name
  # %advancement_title% - Advancement completed
  advancement-done: "**ğŸ… %player_display_name%** has made the advancement **%advancement_title%**"

# Embed colors (Hex: #RRGGBB)
colors:
  server-start: "#00FF00"     # Server startup
  server-stop: "#FF0000"      # Server shutdown
  player-join: "#00FF00"      # Player joined
  player-quit: "#FF0000"      # Player left
  player-death: "#000000"     # Player death
  advancement-done: "#0000FF" # Advancement completed
