
# ==================================================
#                 Bot settings
#  !!Any change here requires a server restart!!
# ==================================================
token: "YOUR_BOT_TOKEN"
chat-channel-id: "YOUR_CHAT_CHANNEL_ID"

# Discord commands mode options
#
#  - MESSAGE â†’ Players can use commands by typing them as normal
#              Discord messages in the "chat-channel-id".
#              Example: "playerlist"
#
#  - SLASH   â†’ Commands are registered as Discord slash commands.
#              Example: "/playerlist"
#
#  - BOTH    â†’ Allows using both message commands and slash commands.
#
#              IMPORTANT!!!!!!
#              When using SLASH mode (or BOTH), this plugin will
#              push its commands to Discord via the REST API.
#              This will REMOVE any existing slash commands on
#              your bot, leaving only the ones from this plugin.
discord-command-mode: BOTH

# ==================================================
#           Minecraft â†’ Discord
#     (What Discord sees from Minecraft)
# ==================================================
minecraft-to-discord:
  # Server startup
  server-start: "**âš¡ Server started**"
  server-start-embed-color: "#00FF00"

  # Server shutdown
  server-stop: "**ğŸ›‘ Server stopped**"
  server-stop-embed-color: "#FF0000"

  # Player chat message
  # Placeholders:
  # %player_name% -> In-game username
  # %player_display_name% -> Display name
  # %message% -> Message sent by player
  player-message: "**%player_display_name%** > %message%"

  # Player joins the server
  # Placeholders:
  # %player_name% -> In-game username
  # %player_display_name% -> Display name
  player-join: "**ğŸŸ¢ %player_display_name%**"
  player-join-embed-color: "#00FF00"

  # Player leaves the server
  # Placeholders:
  # %player_name% -> In-game username
  # %player_display_name% -> Display name
  player-quit: "**ğŸ”´ %player_display_name%**"
  player-quit-embed-color: "#FF0000"

  # Player dies
  # Placeholders:
  # %player_name% -> In-game username
  # %player_display_name% -> Display name
  # %death_message% -> How the player died
  player-death: "**ğŸ’€ %player_display_name%** %death_message%"
  player-death-embed-color: "#000000"

  # Player completes an advancement
  # Placeholders:
  # %player_name% - In-game username
  # %player_display_name% - Display name
  # %advancement_title% - Advancement completed
  advancement-done: "**ğŸ… %player_display_name%** has made the advancement **%advancement_title%**"
  advancement-done-embed-color: "#0000FF"



# ==================================================
#           Discord â†’ Minecraft
#     (What Minecraft sees from Discord)
# ==================================================
discord-to-minecraft:
  # Discord user chats
  # Placeholders:
  # %author_id% -> Discord user's unique ID
  # %author_username% -> Discord user's username
  # %author_displayName% -> Discord user's display name
  # %message% -> Message sent by the user
  user-message: "&9[Discord] &r%author_displayName%: &7%message%"
